repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.711
    hooks:
      - id: mypy
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/gvanderest/pylama-pre-commit
    rev: 0.1.2
    hooks:
      - id: pylama
