"""empty message

Revision ID: 23c853325c67
Revises: 04d0ba21781c
Create Date: 2019-08-26 02:01:48.179142

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '23c853325c67'
down_revision = '04d0ba21781c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column(
                        'month',
                        sa.Enum(
                            'jan',
                            'feb',
                            'mar',
                            'apr',
                            'may',
                            'jun',
                            'jul',
                            'aug',
                            'sep',
                            'oct',
                            'nov',
                            'dec',
                            name='month'),
                        nullable=True),
                    sa.Column('year', sa.Integer(), nullable=True),
                    sa.Column(
                        'issue_tag', sa.String(
                            length=20), nullable=True),
                    sa.Column('cover', sa.Integer(), nullable=True),
                    sa.Column('link', sa.String(length=256), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['cover'], ['imgLink.id'], ),
                    sa.ForeignKeyConstraint(['issue_tag'], ['tag.name'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue')
    # ### end Alembic commands ###
