"""empty message

Revision ID: 48cfa793003b
Revises: 623bd8193309
Create Date: 2019-10-13 18:11:11.114782

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '48cfa793003b'
down_revision = '623bd8193309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('article_summary', sa.Text(), nullable=True),
                    sa.Column('image_link', sa.String(
                        length=255), nullable=True),
                    sa.Column('date', sa.String(length=255), nullable=True),
                    sa.Column('reading_time', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story')
    # ### end Alembic commands ###
