"""empty message

Revision ID: 623bd8193309
Revises: 23c853325c67
Create Date: 2019-08-28 05:04:56.200256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '623bd8193309'
down_revision = '23c853325c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_name', sa.String(length=256), nullable=False))
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.drop_column('post', '_author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('_author_id', mysql.VARCHAR(length=256), nullable=False))
    op.create_foreign_key('post_ibfk_1', 'post', 'user', ['_author_id'], ['username'])
    op.drop_column('post', 'author_name')
    # ### end Alembic commands ###
